### ISSUE TITLE
error when running in GitHub Actions

### ISSUE THREAD

**Issue by dwhieb** [rse/node-prince#45]
I'm trying to use this package in GitHub Actions on Ubuntu-latest, but I keep encountering this error:

`/home/runner/work/<repo-name>/<repo-name>/node_modules/prince/prince/lib/prince/bin/prince: error while loading shared libraries: libavif.so.13: cannot open shared object file: No such file or directory`

I saw issue #33, so I followed the [instructions for installing Prince on Linux](https://www.princexml.com/doc/installing/#installing-prince-on-linuxfreebsd) and added these steps to my GitHub workflow (relevant steps below). No luck. Still getting the same error.

Can you offer any advice on what else I need to do to get node-prince running in GH Actions?

thanks!

```yml
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run:  npm ci

      - name: Update apt
        run:  sudo apt-get update

      - name: Install gdebi-core
        run:  sudo apt install gdebi --fix-missing

      - name: Download Prince
        run:  wget https://www.princexml.com/download/prince_15-1_ubuntu22.04_amd64.deb

      - name: Install Prince
        run:  sudo gdebi prince_15-1_ubuntu22.04_amd64.deb

      - name: Run tests
        run:  npm test

      - name: Build site
        run:  npm run build # <- fails during build with the above error
```
